apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: default
  labels:
    pvc: db
spec:
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce